Table Authors {
  AuthorId int [pk, increment]
  Name varchar(100) [not null]
}

Table Books {
  Id int [pk, increment]
  Title varchar(200) [not null]
  Price decimal(10,2) [not null]
  PublishedDate date [not null]

  AuthorId int [not null]
}

Ref: Books.AuthorId > Authors.AuthorId